export const PATHS = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  PRODUCTION_AREAS: '/production-areas',
  PRODUCTION_AREAS_CREATE: '/production-areas/new',
  PRODUCTION_AREAS_EDIT: '/production-areas/:id/edit',
  PRODUCTION_AREAS_VIEW: '/production-areas/:id',
  // Sedes (solo soporte, fuera del menú): docs/PLAN_SEDES.md §6.4
  SEDES_ADMIN: '/sistema/sedes',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  AUDIT_LOGS: '/audit-logs',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
  CLIENTS: '/clients',
  CLIENTS_CREATE: '/clients/new',
  CLIENTS_EDIT: '/clients/:id/edit',
  CLIENTS_VIEW: '/clients/:id',
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/new',
  SUPPLIERS_EDIT: '/suppliers/:id/edit',
  SUPPLIERS_VIEW: '/suppliers/:id',
  SESSION_LOGS: '/session-logs',
  // Portfolio Routes
  UNITS_OF_MEASURE: '/portfolio/units-of-measure',
  UNITS_OF_MEASURE_CREATE: '/portfolio/units-of-measure/new',
  UNITS_OF_MEASURE_EDIT: '/portfolio/units-of-measure/:id/edit',
  PRODUCT_CATEGORIES: '/portfolio/product-categories',
  PRODUCT_CATEGORIES_CREATE: '/portfolio/product-categories/new',
  PRODUCT_CATEGORIES_EDIT: '/portfolio/product-categories/:id/edit',
  PRODUCTS: '/portfolio/products',
  PRODUCTS_CREATE: '/portfolio/products/new',
  PRODUCTS_EDIT: '/portfolio/products/:id/edit',
  SUPPLY_CATEGORIES: '/portfolio/supply-categories',
  SUPPLY_CATEGORIES_CREATE: '/portfolio/supply-categories/new',
  SUPPLY_CATEGORIES_EDIT: '/portfolio/supply-categories/:id/edit',
  SUPPLIES: '/portfolio/supplies',
  SUPPLIES_CREATE: '/portfolio/supplies/new',
  SUPPLIES_EDIT: '/portfolio/supplies/:id/edit',
  // Orders Routes
  ORDERS: '/orders',
  ORDERS_CREATE: '/orders/new',
  ORDERS_EDIT: '/orders/:id/edit',
  ORDERS_DETAIL: '/orders/:id',
  PENDING_PAYMENT_ORDERS: '/orders/pending-payment',
  STATUS_CHANGE_REQUESTS: '/orders/status-change-requests',
  ORDERS_PROFITABILITY: '/orders/profitability',
  // Order Timeline
  ORDER_FLOW: '/orders/flow/:type/:id',
  ORDER_FLOW_BASE: '/orders/flow',
  // Quotes Routes
  QUOTES: '/quotes',
  QUOTES_CREATE: '/quotes/new',
  QUOTES_EDIT: '/quotes/:id/edit',
  QUOTES_DETAIL: '/quotes/:id',
  // Sales Pipeline (Prospectos)
  PROSPECTS: '/prospects',
  PROSPECT_METRICS: '/prospects/metrics',
  // Commercial Channels Routes
  COMMERCIAL_CHANNELS: '/commercial-channels',
  COMMERCIAL_CHANNELS_CREATE: '/commercial-channels/new',
  COMMERCIAL_CHANNELS_EDIT: '/commercial-channels/:id/edit',
  COMMERCIAL_CHANNELS_VIEW: '/commercial-channels/:id',
  NOTIFICATIONS: '/notifications',
  // Company
  COMPANY: '/company',
  // Work Orders Routes
  WORK_ORDERS: '/work-orders',
  WORK_ORDERS_CREATE: '/work-orders/new',
  WORK_ORDERS_EDIT: '/work-orders/:id/edit',
  WORK_ORDERS_DETAIL: '/work-orders/:id',
  // Expense Types & Subcategories Routes
  EXPENSE_TYPES: '/expense-types',
  EXPENSE_TYPES_CREATE: '/expense-types/new',
  EXPENSE_TYPES_EDIT: '/expense-types/:id/edit',
  EXPENSE_SUBCATEGORIES: '/expense-subcategories',
  EXPENSE_SUBCATEGORIES_CREATE: '/expense-subcategories/new',
  EXPENSE_SUBCATEGORIES_EDIT: '/expense-subcategories/:id/edit',
  // Expense Orders Routes
  EXPENSE_ORDERS: '/expense-orders',
  EXPENSE_ORDERS_CREATE: '/expense-orders/new',
  EXPENSE_ORDERS_EDIT: '/expense-orders/:id/edit',
  EXPENSE_ORDERS_DETAIL: '/expense-orders/:id',
  // Payroll Routes
  PAYROLL_EMPLOYEES: '/payroll/employees',
  PAYROLL_EMPLOYEES_CREATE: '/payroll/employees/create',
  PAYROLL_EMPLOYEES_EDIT: '/payroll/employees/:id/edit',
  PAYROLL_EMPLOYEES_HISTORY: '/payroll/employees/:id/history',
  PAYROLL_DEDUCTIONS: '/payroll/deductions',
  PAYROLL_PERIODS: '/payroll/periods',
  PAYROLL_PERIODS_CREATE: '/payroll/periods/create',
  PAYROLL_PERIODS_EDIT: '/payroll/periods/:id/edit',
  PAYROLL_PERIODS_DETAIL: '/payroll/periods/:id',
  PAYROLL_ITEM_EDIT: '/payroll/periods/:periodId/items/:itemId/edit',
  CHANGE_PASSWORD: '/change-password',
  // Attendance - Control de Asistencia
  MY_ATTENDANCE: '/my-attendance',
  ATTENDANCE: '/attendance',
  // Inventory - Movimientos de Inventario
  INVENTORY_MOVEMENTS: '/inventory/movements',
  INVENTORY_MOVEMENTS_NEW: '/inventory/movements/new',
  INVENTORY_LOW_STOCK: '/inventory/low-stock',
  // Production Module
  PRODUCT_TEMPLATES: '/production/templates',
  PRODUCT_TEMPLATES_CREATE: '/production/templates/new',
  PRODUCT_TEMPLATES_DETAIL: '/production/templates/:id',
  PRODUCT_TEMPLATES_EDIT: '/production/templates/:id/edit',
  PRODUCTION_ORDERS: '/production/orders',
  PRODUCTION_ORDERS_CREATE: '/production/orders/new',
  PRODUCTION_ORDERS_DETAIL: '/production/orders/:id',
  STEP_DEFINITIONS: '/production/step-definitions',
  STEP_DEFINITIONS_BUILDER: '/production/step-definitions/:id/builder',
  // Cash Register (POS)
  CASH_REGISTERS: '/cash-register/admin',
  CASH_SESSION_OPEN: '/cash-register/open',
  CASH_SESSION_ACTIVE_BASE: '/cash-register/session',
  CASH_SESSION_ACTIVE: '/cash-register/session/:id',
  CASH_SESSION_CLOSE: '/cash-register/session/:id/close',
  CASH_SESSION_HISTORY: '/cash-register/history',
  CASH_SESSION_HISTORY_DETAIL: '/cash-register/history/:id',
  // Cuentas por Pagar
  ACCOUNTS_PAYABLE: '/accounts-payable',
  ACCOUNTS_PAYABLE_NEW: '/accounts-payable/new',
  ACCOUNTS_PAYABLE_DETAIL: '/accounts-payable/:id',
  ACCOUNTS_PAYABLE_EDIT: '/accounts-payable/:id/edit',
  // DTF
  DTF: '/dtf',
  DTF_CREATE: '/dtf/create',
  DTF_DETAIL: '/dtf/:id',
  DTF_EDIT: '/dtf/:id/edit',
  // Approval Redirect (WhatsApp CTA)
  APPROVAL_REDIRECT: '/approvals/:id',
  // Ventas por Asesor
  SALES_BY_ADVISOR: '/ventas-por-asesor',
  SALES_BY_ADVISOR_DETAIL: '/ventas-por-asesor/:advisorId',
};

