export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  USER: 'user',
  THEME: 'theme',
};

export const PERMISSIONS = {
  CREATE_USERS: 'create_users',
  READ_USERS: 'read_users',
  UPDATE_USERS: 'update_users',
  DELETE_USERS: 'delete_users',
  CREATE_ROLES: 'create_roles',
  READ_ROLES: 'read_roles',
  UPDATE_ROLES: 'update_roles',
  DELETE_ROLES: 'delete_roles',
  CREATE_PERMISSIONS: 'create_permissions',
  READ_PERMISSIONS: 'read_permissions',
  UPDATE_PERMISSIONS: 'update_permissions',
  DELETE_PERMISSIONS: 'delete_permissions',
  MANAGE_PERMISSIONS: 'manage_permissions',
  CREATE_CARGOS: 'create_cargos',
  READ_CARGOS: 'read_cargos',
  UPDATE_CARGOS: 'update_cargos',
  DELETE_CARGOS: 'delete_cargos',
  CREATE_PRODUCTION_AREAS: 'create_production_areas',
  READ_PRODUCTION_AREAS: 'read_production_areas',
  UPDATE_PRODUCTION_AREAS: 'update_production_areas',
  DELETE_PRODUCTION_AREAS: 'delete_production_areas',
  READ_AUDIT_LOGS: 'read_audit_logs',
  READ_SESSION_LOGS: 'read_session_logs',
  CREATE_SUPPLIERS: 'create_suppliers',
  READ_SUPPLIERS: 'read_suppliers',
  UPDATE_SUPPLIERS: 'update_suppliers',
  DELETE_SUPPLIERS: 'delete_suppliers',
  CREATE_CLIENTS: 'create_clients',
  READ_CLIENTS: 'read_clients',
  EXPORT_CLIENTS: 'export_clients',
  BROWSE_CLIENTS: 'browse_clients',
  UPDATE_CLIENTS: 'update_clients',
  DELETE_CLIENTS: 'delete_clients',
  UPDATE_CLIENT_SPECIAL_CONDITION: 'update_client_special_condition',
  SEARCH_CLIENTS: 'search_clients',
  // Portfolio - Units of Measure
  CREATE_UNITS_OF_MEASURE: 'create_units_of_measure',
  READ_UNITS_OF_MEASURE: 'read_units_of_measure',
  UPDATE_UNITS_OF_MEASURE: 'update_units_of_measure',
  DELETE_UNITS_OF_MEASURE: 'delete_units_of_measure',
  // Portfolio - Product Categories
  CREATE_PRODUCT_CATEGORIES: 'create_product_categories',
  READ_PRODUCT_CATEGORIES: 'read_product_categories',
  UPDATE_PRODUCT_CATEGORIES: 'update_product_categories',
  DELETE_PRODUCT_CATEGORIES: 'delete_product_categories',
  // Portfolio - Products
  CREATE_PRODUCTS: 'create_products',
  READ_PRODUCTS: 'read_products',
  UPDATE_PRODUCTS: 'update_products',
  DELETE_PRODUCTS: 'delete_products',
  // Portfolio - Supply Categories
  CREATE_SUPPLY_CATEGORIES: 'create_supply_categories',
  READ_SUPPLY_CATEGORIES: 'read_supply_categories',
  UPDATE_SUPPLY_CATEGORIES: 'update_supply_categories',
  DELETE_SUPPLY_CATEGORIES: 'delete_supply_categories',
  // Portfolio - Supplies
  CREATE_SUPPLIES: 'create_supplies',
  READ_SUPPLIES: 'read_supplies',
  UPDATE_SUPPLIES: 'update_supplies',
  DELETE_SUPPLIES: 'delete_supplies',
  // Orders
  CREATE_ORDERS: 'create_orders',
  READ_ORDERS: 'read_orders',
  READ_ORDERS_DASHBOARD: 'read_orders_dashboard',
  EXPORT_ORDERS: 'export_orders',
  EXPORT_PENDING_PAYMENT_ORDERS: 'export_pending_payment_orders',
  EXPORT_PROFITABILITY: 'export_profitability',
  UPDATE_ORDERS: 'update_orders',
  DELETE_ORDERS: 'delete_orders',
  APPROVE_ORDERS: 'approve_orders',
  CHANGE_ORDER_STATUS: 'change_order_status',
  REQUEST_ADVISOR_CHANGE: 'request_advisor_change',
  APPROVE_ADVISOR_CHANGE: 'approve_advisor_change',
  REQUEST_QUOTE_RESTORE: 'request_quote_restore',
  APPROVE_QUOTE_RESTORE: 'approve_quote_restore',
  REGISTER_ORDER_PAYMENTS: 'register_order_payments',
  READ_PENDING_ORDERS: 'read_pending_orders',
  APPROVE_ADVANCE_PAYMENTS: 'approve_advance_payments',
  APPLY_DISCOUNTS: 'apply_discounts',
  APPROVE_DISCOUNTS: 'approve_discounts',
  APPROVE_CLIENT_OWNERSHIP_AUTH: 'approve_client_ownership_auth',
  REQUEST_CLIENT_ADVISOR: 'request_client_advisor',
  APPROVE_CLIENT_ADVISOR: 'approve_client_advisor',
  CREATE_REFUND_REQUESTS: 'create_refund_requests',
  APPROVE_REFUNDS: 'approve_refunds',
  EXECUTE_REFUNDS: 'execute_refunds',
  //READ_COMMERCIAL_CHANNELS
  READ_COMMERCIAL_CHANNELS: 'read_commercial_channels',
  CREATE_COMMERCIAL_CHANNELS: 'create_commercial_channels',
  UPDATE_COMMERCIAL_CHANNELS: 'update_commercial_channels',
  DELETE_COMMERCIAL_CHANNELS: 'delete_commercial_channels',
  // Quotes
  CREATE_QUOTES: 'create_quotes',
  READ_QUOTES: 'read_quotes',
  EXPORT_QUOTES: 'export_quotes',
  UPDATE_QUOTES: 'update_quotes',
  DELETE_QUOTES: 'delete_quotes',
  CONVERT_QUOTES: 'convert_quotes',
  MANAGE_QUOTE_COLUMNS: 'manage_quote_columns',
  READ_ALL_QUOTES: 'read_all_quotes',
  // Sales Pipeline (Prospectos)
  CREATE_PROSPECTS: 'create_prospects',
  READ_PROSPECTS: 'read_prospects',
  READ_ALL_PROSPECTS: 'read_all_prospects',
  UPDATE_PROSPECTS: 'update_prospects',
  DELETE_PROSPECTS: 'delete_prospects',
  CONVERT_PROSPECTS: 'convert_prospects',
  EXPORT_PROSPECTS: 'export_prospects',
  READ_PROSPECT_METRICS: 'read_prospect_metrics',
  // Company
  READ_COMPANY: 'read_company',
  UPDATE_COMPANY: 'update_company',
  // Work Orders
  CREATE_WORK_ORDERS: 'create_work_orders',
  READ_WORK_ORDERS: 'read_work_orders',
  EXPORT_WORK_ORDERS: 'export_work_orders',
  UPDATE_WORK_ORDERS: 'update_work_orders',
  DELETE_WORK_ORDERS: 'delete_work_orders',
  // Expense Types
  CREATE_EXPENSE_TYPES: 'create_expense_types',
  READ_EXPENSE_TYPES: 'read_expense_types',
  UPDATE_EXPENSE_TYPES: 'update_expense_types',
  DELETE_EXPENSE_TYPES: 'delete_expense_types',
  // Expense Orders
  CREATE_EXPENSE_ORDERS: 'create_expense_orders',
  READ_EXPENSE_ORDERS: 'read_expense_orders',
  EXPORT_EXPENSE_ORDERS: 'export_expense_orders',
  UPDATE_EXPENSE_ORDERS: 'update_expense_orders',
  DELETE_EXPENSE_ORDERS: 'delete_expense_orders',
  APPROVE_EXPENSE_ORDERS: 'approve_expense_orders',
  CAJA_AUTHORIZE_EXPENSE_ORDERS: 'caja_authorize_expense_orders',
  // Payroll - Empleados de nómina
  CREATE_PAYROLL_EMPLOYEES: 'create_payroll_employees',
  READ_PAYROLL_EMPLOYEES: 'read_payroll_employees',
  UPDATE_PAYROLL_EMPLOYEES: 'update_payroll_employees',
  DELETE_PAYROLL_EMPLOYEES: 'delete_payroll_employees',
  // Payroll - Periodos de nómina
  CREATE_PAYROLL_PERIODS: 'create_payroll_periods',
  READ_PAYROLL_PERIODS: 'read_payroll_periods',
  UPDATE_PAYROLL_PERIODS: 'update_payroll_periods',
  DELETE_PAYROLL_PERIODS: 'delete_payroll_periods',
  // Descuentos de OP por nómina
  READ_PAYROLL_DEDUCTIONS: 'read_payroll_deductions',
  APPROVE_PAYROLL_DEDUCTIONS: 'approve_payroll_deductions',
  APPLY_PAYROLL_DEDUCTIONS: 'apply_payroll_deductions',
  // Attendance - Control de Asistencia
  USE_ATTENDANCE: 'use_attendance',
  READ_ATTENDANCE: 'read_attendance',
  MANAGE_ATTENDANCE: 'manage_attendance',
  // Inventory - Movimientos de Inventario
  CREATE_INVENTORY_MOVEMENTS: 'create_inventory_movements',
  READ_INVENTORY_MOVEMENTS: 'read_inventory_movements',
  MANAGE_INVENTORY: 'manage_inventory',
  // Production Module — Plantillas de Producto
  READ_PRODUCT_TEMPLATES: 'read_product_templates',
  CREATE_PRODUCT_TEMPLATES: 'create_product_templates',
  UPDATE_PRODUCT_TEMPLATES: 'update_product_templates',
  DELETE_PRODUCT_TEMPLATES: 'delete_product_templates',
  READ_STEP_DEFINITIONS: 'read_step_definitions',
  CREATE_STEP_DEFINITIONS: 'create_step_definitions',
  UPDATE_STEP_DEFINITIONS: 'update_step_definitions',
  // Production Module — Órdenes de Producción
  READ_PRODUCTION_ORDERS: 'read_production_orders',
  CREATE_PRODUCTION_ORDERS: 'create_production_orders',
  UPDATE_PRODUCTION_ORDERS: 'update_production_orders',
  // Comments — Comentarios polimórficos (COT / OP / OT)
  CREATE_COMMENTS: 'create_comments',
  READ_COMMENTS: 'read_comments',
  DELETE_COMMENTS: 'delete_comments',
  // Cash Register — Caja Registradora (POS)
  CREATE_CASH_REGISTERS: 'create_cash_registers',
  READ_CASH_REGISTERS: 'read_cash_registers',
  UPDATE_CASH_REGISTERS: 'update_cash_registers',
  DELETE_CASH_REGISTERS: 'delete_cash_registers',
  OPEN_CASH_SESSION: 'open_cash_session',
  CLOSE_CASH_SESSION: 'close_cash_session',
  READ_CASH_SESSIONS: 'read_cash_sessions',
  CREATE_CASH_MOVEMENTS: 'create_cash_movements',
  VOID_CASH_MOVEMENTS: 'void_cash_movements',
  REQUEST_PAYMENT_VOID: 'request_payment_void',
  APPROVE_CASH_MOVEMENTS: 'approve_cash_movements',
  READ_CASH_MOVEMENTS: 'read_cash_movements',
  // Cuentas por Pagar
  CREATE_ACCOUNTS_PAYABLE: 'create_accounts_payable',
  READ_ACCOUNTS_PAYABLE: 'read_accounts_payable',
  EXPORT_ACCOUNTS_PAYABLE: 'export_accounts_payable',
  UPDATE_ACCOUNTS_PAYABLE: 'update_accounts_payable',
  DELETE_ACCOUNTS_PAYABLE: 'delete_accounts_payable',
  REGISTER_AP_PAYMENT: 'register_ap_payment',
  APPROVE_ACCOUNTS_PAYABLE: 'approve_accounts_payable',
  CAJA_AUTHORIZE_AP_PAYMENT: 'caja_authorize_ap_payment',
  REQUEST_AP_PAYMENT_REVERSAL: 'request_ap_payment_reversal',
  GERENCIA_APPROVE_AP_PAYMENT_REVERSAL: 'gerencia_approve_ap_payment_reversal',
  CAJA_CONFIRM_AP_PAYMENT_REVERSAL: 'caja_confirm_ap_payment_reversal',
  // Dashboard Financiero
  READ_FINANCIAL_DASHBOARD: 'read_financial_dashboard',
  // DTF
  READ_DTF: 'read_dtf',
  EXPORT_DTF: 'export_dtf',
  CREATE_DTF: 'create_dtf',
  UPDATE_DTF: 'update_dtf',
  CHANGE_DTF_STATUS: 'change_dtf_status',
  CONVERT_DTF_TO_ORDER: 'convert_dtf_to_order',
  // Ventas por Asesor / Metas
  READ_SALES_BY_ADVISOR: 'read_sales_by_advisor',
  EXPORT_SALES_BY_ADVISOR: 'export_sales_by_advisor',
  MANAGE_SALES_GOALS: 'manage_sales_goals',
  READ_ALL_ADVISORS_TRACKING: 'read_all_advisors_tracking',
  // Sedes (solo Zoom). MANAGE_LOCATIONS es reservado a soporte.
  VIEW_ALL_LOCATIONS: 'view_all_locations',
  READ_OTHER_LOCATIONS: 'read_other_locations',
  MANAGE_USER_LOCATIONS: 'manage_user_locations',
  READ_ALL_CASH_SESSIONS: 'read_all_cash_sessions',
  PERFORM_GENERAL_CLOSING: 'perform_general_closing',
  MANAGE_LOCATIONS: 'manage_locations',
};

export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  /** Dashboard consolidado por sede (solo Zoom, docs/PLAN_SEDES.md §7). */
  DASHBOARD_SEDES: '/dashboard/sedes',
  USERS: '/users',
  USERS_CREATE: '/users/create',
  USERS_EDIT: '/users/:id/edit',
  USERS_VIEW: '/users/:id',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: '/roles/:id/edit',
  ROLES_PERMISSIONS: '/roles/:id/permissions',
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: '/permissions/:id/edit',
  CARGOS: '/cargos',
  CARGOS_CREATE: '/cargos/new',
  CARGOS_EDIT: '/cargos/:id/edit',
  CARGOS_VIEW: '/cargos/:id',
  PRODUCTION_AREAS: '/production-areas',
  PRODUCTION_AREAS_CREATE: '/production-areas/new',
  PRODUCTION_AREAS_EDIT: '/production-areas/:id/edit',
  PRODUCTION_AREAS_VIEW: '/production-areas/:id',
  AUDIT_LOGS: '/audit-logs',
  SESSION_LOGS: '/session-logs',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  NOT_FOUND: '/not-found',
  UNAUTHORIZED: '/unauthorized',
  SUPPLIERS: '/suppliers',
  SUPPLIERS_CREATE: '/suppliers/new',
  SUPPLIERS_EDIT: '/suppliers/:id/edit',
  SUPPLIERS_VIEW: '/suppliers/:id',
  // clients
  CLIENTS: '/clients',
  CLIENTS_CREATE: '/clients/new',
  CLIENTS_EDIT: '/clients/:id/edit',
  CLIENTS_VIEW: '/clients/:id',
  // Portfolio
  UNITS_OF_MEASURE: '/portfolio/units-of-measure',
  UNITS_OF_MEASURE_CREATE: '/portfolio/units-of-measure/new',
  UNITS_OF_MEASURE_EDIT: '/portfolio/units-of-measure/:id/edit',
  PRODUCT_CATEGORIES: '/portfolio/product-categories',
  PRODUCT_CATEGORIES_CREATE: '/portfolio/product-categories/new',
  PRODUCT_CATEGORIES_EDIT: '/portfolio/product-categories/:id/edit',
  PRODUCTS: '/portfolio/products',
  PRODUCTS_CREATE: '/portfolio/products/new',
  PRODUCTS_EDIT: '/portfolio/products/:id/edit',
  SUPPLY_CATEGORIES: '/portfolio/supply-categories',
  SUPPLY_CATEGORIES_CREATE: '/portfolio/supply-categories/new',
  SUPPLY_CATEGORIES_EDIT: '/portfolio/supply-categories/:id/edit',
  SUPPLIES: '/portfolio/supplies',
  SUPPLIES_CREATE: '/portfolio/supplies/new',
  SUPPLIES_EDIT: '/portfolio/supplies/:id/edit',
  // Orders
  ORDERS: '/orders',
  ORDERS_CREATE: '/orders/new',
  ORDERS_EDIT: '/orders/:id/edit',
  ORDERS_DETAIL: '/orders/:id',
  PENDING_PAYMENT_ORDERS: '/orders/pending-payment',
  STATUS_CHANGE_REQUESTS: '/orders/status-change-requests',
  ORDERS_PROFITABILITY: '/orders/profitability',
  // Order Timeline
  ORDER_FLOW: '/orders/flow/:type/:id',
  ORDER_FLOW_BASE: '/orders/flow',
  // Quotes
  QUOTES: '/quotes',
  QUOTES_CREATE: '/quotes/new',
  QUOTES_EDIT: '/quotes/:id/edit',
  QUOTES_DETAIL: '/quotes/:id',
  // Sales Pipeline (Prospectos)
  PROSPECTS: '/prospects',
  PROSPECT_METRICS: '/prospects/metrics',
  // Company
  COMPANY: '/company',
  // Work Orders
  WORK_ORDERS: '/work-orders',
  WORK_ORDERS_CREATE: '/work-orders/new',
  WORK_ORDERS_DETAIL: '/work-orders/:id',
  WORK_ORDERS_EDIT: '/work-orders/:id/edit',
  // Expense Types & Subcategories
  EXPENSE_TYPES: '/expense-types',
  EXPENSE_TYPES_CREATE: '/expense-types/new',
  EXPENSE_TYPES_EDIT: '/expense-types/:id/edit',
  EXPENSE_SUBCATEGORIES: '/expense-subcategories',
  EXPENSE_SUBCATEGORIES_CREATE: '/expense-subcategories/new',
  EXPENSE_SUBCATEGORIES_EDIT: '/expense-subcategories/:id/edit',
  // Expense Orders
  EXPENSE_ORDERS: '/expense-orders',
  EXPENSE_ORDERS_CREATE: '/expense-orders/new',
  EXPENSE_ORDERS_EDIT: '/expense-orders/:id/edit',
  EXPENSE_ORDERS_DETAIL: '/expense-orders/:id',
  // Payroll
  PAYROLL_EMPLOYEES: '/payroll/employees',
  PAYROLL_EMPLOYEES_CREATE: '/payroll/employees/create',
  PAYROLL_EMPLOYEES_EDIT: '/payroll/employees/:id/edit',
  PAYROLL_EMPLOYEES_HISTORY: '/payroll/employees/:id/history',
  PAYROLL_DEDUCTIONS: '/payroll/deductions',
  PAYROLL_PERIODS: '/payroll/periods',
  PAYROLL_PERIODS_CREATE: '/payroll/periods/create',
  PAYROLL_PERIODS_EDIT: '/payroll/periods/:id/edit',
  PAYROLL_PERIODS_DETAIL: '/payroll/periods/:id',
  PAYROLL_ITEM_EDIT: '/payroll/periods/:periodId/items/:itemId/edit',
  // Attendance
  MY_ATTENDANCE: '/my-attendance',
  ATTENDANCE: '/attendance',
  // Inventory
  INVENTORY_MOVEMENTS: '/inventory/movements',
  INVENTORY_MOVEMENTS_NEW: '/inventory/movements/new',
  INVENTORY_LOW_STOCK: '/inventory/low-stock',
  // Production Module
  PRODUCT_TEMPLATES: '/production/templates',
  PRODUCT_TEMPLATES_CREATE: '/production/templates/new',
  PRODUCT_TEMPLATES_DETAIL: '/production/templates/:id',
  PRODUCT_TEMPLATES_EDIT: '/production/templates/:id/edit',
  PRODUCTION_ORDERS: '/production/orders',
  PRODUCTION_ORDERS_CREATE: '/production/orders/new',
  PRODUCTION_ORDERS_DETAIL: '/production/orders/:id',
  STEP_DEFINITIONS: '/production/step-definitions',
  STEP_DEFINITIONS_BUILDER: '/production/step-definitions/:id/builder',
  // Cash Register (POS)
  CASH_REGISTERS: '/cash-register/admin',
  CASH_SESSION_OPEN: '/cash-register/open',
  CASH_SESSION_ACTIVE_BASE: '/cash-register/session',
  CASH_SESSION_ACTIVE: '/cash-register/session/:id',
  CASH_SESSION_CLOSE: '/cash-register/session/:id/close',
  CASH_SESSION_HISTORY: '/cash-register/history',
  CASH_SESSION_HISTORY_DETAIL: '/cash-register/history/:id',
  // Cuentas por Pagar
  ACCOUNTS_PAYABLE: '/accounts-payable',
  ACCOUNTS_PAYABLE_NEW: '/accounts-payable/new',
  ACCOUNTS_PAYABLE_DETAIL: '/accounts-payable/:id',
  ACCOUNTS_PAYABLE_EDIT: '/accounts-payable/:id/edit',
  // DTF
  DTF: '/dtf',
  DTF_CREATE: '/dtf/create',
  DTF_DETAIL: '/dtf/:id',
  DTF_EDIT: '/dtf/:id/edit',
  // Ventas por Asesor
  SALES_BY_ADVISOR: '/ventas-por-asesor',
  SALES_BY_ADVISOR_DETAIL: '/ventas-por-asesor/:advisorId',
};

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 10,
};

/**
 * Entidades bancarias / billeteras disponibles como origen de un pago
 * por transferencia. Se usan en el BankSelector de todos los formularios de pago.
 */
export const BANKS: string[] = [
  'Bancolombia',
  'Nequi',
  'Davivienda',
  'Daviplata',
  'Banco de Bogotá',
  'BBVA Colombia',
  'Banco de Occidente',
  'Banco AV Villas',
  'Banco Popular',
  'Banco Caja Social',
  'Banco Agrario',
  'Banco Falabella',
  'Banco Itaú',
  'Bancamía',
  'Banco W',
  'Banco Mundo Mujer',
  'Banco Serfinanza',
  'Banco Finandina',
  'Banco Contactar',
  'Banco Unión',
  'Banco Sudameris',
  'BAN100',
  'Lulo Bank',
  'Nu Colombia (Nubank)',
  'RappiPay',
  'Ualá',
  'Movii',
  'Dale!',
  'Coink',
];
